server:
  port: 8081

jasypt:
  encryptor:
    password: e!swhdg&d763jo

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 20
        min-idle: 5
        max-wait: 5000ms
        max-idle: 20
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sureness?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    platform: mysql
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    # 每次重启都会根据data.sql schema.sql重建表数据, 设置 NEVER 就不启动重建
    # Each restart will rebuild the table data according to data.sql schema.sql
    # setting NEVER will not start the reconstruction
    initialization-mode: NEVER
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
    minimum-idle: 5
    maximum-pool-size: 500
    idle-timeout: 600000
  jpa:
    database: mysql
    show-sql: true

